namespace UniConnect.Models.Entities;

public class Attendee
{
    public int Id { get; set; } // Auto generated by DB
    public required int UserId { get; set; } // ID of the user who created the event
    public required int EventId { get; set; } // ID of the event the person will attend
    public required User User { get; set; } // The user
    public required Event Event { get; set; } // The event
}