namespace UniConnect.Models.Entities;

public class Comment
{
    public int Id { get; set; } // Auto generated by DB
    public required User User { get; set; } // The commenter
    public required Post Post { get; set; } // The post
    public required string CommentText { get; set; } // The text content of the comment
    public required DateTime CreationDate { get; set; } // Auto generated on creation
    public int? ParentCommentId { get; set; } // The ID the comment that this comment is replying to. Null if it's a top-level comment
    public List<Comment> Replies { get; set; } = new(); // List of replies to this comment
}