namespace UniConnect.Models.Entities;

public class FriendRequest
{
    public int Id { get; set; } // Auto generated by db
    public required User Sender { get; set; }
    public required User Receiver { get; set; }
}