namespace UniConnect.Models.Entities;

public class Friendship
{
    public int Id { get; set; } // Auto generated by db
    public required int UserId { get; set; }
    public required User User { get; set; }
    public required int FriendId { get; set; }
    public required User Friend { get; set; }
    public required DateTime CreationDate { get; set; }
}