namespace UniConnect.Models.Entities;

public class Like
{
    public int Id { get; set; } // Auto generated by DB
    public required int UserId { get; set; } // Id of the user who liked the post
    public required int PostId { get; set; } // Id of the post that was liked
    public required User User { get; set; } // User that liked the post
    public required Post Post { get; set; } // Post that was liked
}