namespace UniConnect.Models.Entities;

public class Post
{
    public int Id { get; set; } // Auto generated by DB
    public required User User { get; set; } // The user who posted
    public required string Text { get; set; } // The text content in the post
    public string? Image { get; set; } // The image in the post (optional). Stored as URL.
    public required DateTime CreationDate { get; set; } // Auto generated on creation
    public List<Like> Likes { get; set; } = new(); // Stores likes from the DB that has the post ID
    public List<Comment> Comments { get; set; } = new(); // Stores comments from the DB that has the post ID
    public Event? Event { get; set; } // Stores the embedded event if the post includes one
}