namespace UniConnect.Models.Entities;

public class Save
{
    public int Id { get; set; } // Auto generated by DB
    public required int UserId { get; set; } // Id of the user who saved the post
    public required int PostId { get; set; } // Id of the post that was saved
    public required User User { get; set; } // User that saved the post
    public required Post Post { get; set; } // Post that was saved
}