namespace UniConnect.Models;

public class Like
{
    public int Id { get; set; } // Auto generated by DB
    public required int UserId { get; set; } // User ID of the person who liked the post
    public required int PostId { get; set; } // ID of the post that was liked
    public required User User { get; set; } // User that liked the post
    public required Post Post { get; set; } // Post that was liked
}