namespace UniConnect.Models;

using System.ComponentModel.DataAnnotations;

public class User
{
    public int Id { get; set; } // Auto generated by DB
    public Role Role { get; set; } = Role.Student; // Role is student by default
    public required string Username { get; set; } // Auto generated based on email then adds a number if the username exists. Change to lowercase before storing.
    public required string PasswordHash { get; set; } // Password is hashed with salt before stored
    public required string FirstName { get; set; } // From user input during registration (verified by checking email to avoid fake names)
    public required string LastName { get; set; } // From user input during registration (verified by checking email to avoid fake names)
    [EmailAddress]
    public required string Email { get; set; } // From user input during registration. Change to lowercase before storing.
    public required string Degree { get; set; } // From user input during registration (store as an enum in the future)
    public string? ProfileImageURL { get; set; } // Updated in edit profile page
    public required DateTime CreationDate { get; set; } // Auto generated on registration
    public List<Post> Posts { get; set; } = new(); // Stores posts created by the user
    public List<Comment> Comments { get; set; } = new(); // Stores comments sent by the user
    public bool IsDeactivated { get; set; } = false; // Deactivate by default. Delete after inactivity.
    public DateTime? DeactivatedDate { get; set; } // Keep track of when the account was deactivated to delete after a period of inactivity. Null if the account is active.
}